### ISSUE TITLE
ध्व॒नि॒स॒ञ्चि॒का

### ISSUE THREAD

**Issue by ujjvlh** [031323/suvak#1]
लि॒खि॒तमा॒दाय॒ तेन॑ ध्वनिसञ्चि॒का यथा॒ कर्तुं॑ श॒क्येत॒ तत् "पठ॑मा॒" इत्यत्र॒ निर्दि॑श्यताम्। @utkrssh

**Comment by utkrssh** [comment]
इ॒दानी॒[मत्र॑](https://031323.github.io/suvak/index3.html)नोदन॒कम्प्रद॑त्तम्।
