### ISSUE TITLE
उ॒दात्ता॑नामुदात्त॒त्वम्

### ISSUE THREAD

**Issue by ujjvlh** [031323/suvak#3]
उ॒दा॒त्त॒स्व॒राणा॑मुदात्त॒त्वं क॒थं परि॑वर्तयितुं शक्येत? जा॒ल॒स्था॒न ए॒वोदा॑त्ततापरि॒वर्त॑नाय॒ किञ्चि॑द् योज॒नीय॑म्। @utkrssh

**Comment by utkrssh** [comment]
यो॒जि॒तम्।
[अत्र॑](https://031323.github.io/suvak/index2) Developer Console इत्य॒स्मिन् `suvak_svr0`, `suvak_svr1` इत्ये॒तौ प॑रिवर्त॒नीयौ॑।
https://github.com/031323/suvak/blob/449c36d28b4b28dc5cc54d8a0d50a06e630f52cf/hts/lib/suvak2.js#L75
