### ISSUE TITLE
स्व॒रि॒तः

### ISSUE THREAD

**Issue by ujjvlh** [031323/suvak#4]
वि॒श्वा॒स॒म॒हो॒द॒यः स्व॑रि॒तस्या॒द्यश्चान्ते॑ च॒ यः स्व॒रस्तौ पृ॑थ॒क्तया॑ परि॑वर्तयितुमिच्छति। @utkrssh

**Comment by utkrssh** [comment]
अ॒नु॒दा॒त्तो॒त्त॒रस्य॑ स्वरि॒तस्य॑ स्व॒रौ परि॑वर्तयितु॒मत्र॑ "-1" इत्य॒स्मिन् स्थाने॑ इ॒ष्टो लि॑खित॒व्यः॑।
https://github.com/031323/suvak/blob/449cab1f238a4f9e7e768efc4eb9d5237f5d137c/hts/lib/suvak2.js#L81-L84
उ॒दा॒त्तो॒त्त॒रस्य॑ स्वरि॒तस्य॑ स्व॒रौ परि॑वर्तयितुं वि॒धानं॑ चि॒रेण॑ विधास्यामि।

**Comment by utkrssh** [comment]
उ॒दा॒त्तो॒त्त॒रस्य॑ स्वरि॒तस्य॑ स्व॒रावपि॑ परि॑वर्तयितु॒मत्र॑ "true" इति॑ लिखित॒व्य॑म्।
https://github.com/031323/suvak/blob/0c3f6ef1002fdf92a189375dc5b3ff9fdfc65826/hts/lib/suvak2.js#L87
ए॒ते सर्वे॑ "var" स॒न्ति॒ तस्मा॑द् बाह्यवि॒धिना॑ क॒दापि॒ परि॑वर्तयितुं शक्यन्ते।

**Comment by kashcit** [comment]
`suvak_svr0=100,suvak_svr1=135` इति स्थितिम् उदाहृत्य स्ववाञ्छां स्पष्टीकरोमि।

उच्चैर् उदात्तो नीचैर् अनुदात्तस् समाहारस् स्वरित इत्याह पाणिनिः। नाम स्वरितस्योच्चारणे स्वरस्योच्चता पतेत् 135त आरभ्य 100 यावत्। अस्य मसृणं साधनम् इष्टतमम् (tone should fall smoothly - like a slanted line)। तत्साधने क्लेषे सति step-function-रूपेण शक्यं वा साधयितुम्? नाम - स्वरितस्य यस्यकस्यचित् पूर्वार्धे 135 इति स्यात् स्तरः, उत्तरार्धे 100 इति। न ह्य् अनेन परिविषिस्वरेषु कश्चन परिणामस् स्यात्। 

अप्य् अपेक्षा मदीया स्पष्टा?

**Comment by ujjvlh** [comment]
प्र॒थ॒मं ताव॑दि॒मे ज्ञा॑त॒व्या३॒॑ अत्र॑-

`suvak_svr1` नामो॒दात्तः॑।
`suvak_svr0` नामानु॑दात्तः। (किन्तु- )
`suvak_udattpurvanudatth` नाम॑ स॒न्नत॑रः। (यदि॒ तत् `-1` नास्ति॑। `-1` अस्ति॒ चेत् `suvak_svr0` ए॒व स॒न्नत॑रः।)

`udattadnudattsysvrith` इ॒दं स॒त्यं (`true`) क्रि॑यताम्। अ॒नेनो॒दात्ता॒दनु॑दात्तः स्वरि॒तः क्रि॑यते।

`suvak_svritoddath` नाम॑ स्वरि॒तस्या॑दिस्व॒रः। (यदि॒ तत् `-1` नास्ति॑। `-1` अस्ति॒ चेत् `suvak_svr1` ए॒व स्व॑रिता॒दिः।)
`suvak_svritanudatth` नाम॑ स्वरि॒तस्या॑न्तस्व॒रः। (यदि॒ तत् `-1` नास्ति॑। `-1` अस्ति॒ चेत् `suvak_svr0` ए॒व स्व॑रिता॒न्तः।)

स्व॒रि॒त आ॑दिस्व॒राद् अ॑न्तस्व॒रं प्रति॒ शनै॑रे॒व प॑तति। न ह्यत्र॑ स्वरि॒तो द्विधा॒ विभ॑क्तः। वद॑तु @kashcit, इ॒ष्यते॑ वा॒ द्विधा॒ विभ॑क्तः पूर्वार्धोत्तरा॒र्धयोः॑?

**Comment by kashcit** [comment]
स्पष्टम् अधुना।

```
suvak_svr1
150
suvak_svr0
100
suvak_udattpurvanudatth=95
95
udattadnudattsysvrith=true
true
```

इति विहितम्। सिद्धम् एवेष्टम्। 

उच्चारण-वेगम् परिवर्तयितुं किञ्चिद् इष्यते विधानम्, यथा येन ७५% वेगेन ५०% वेगेन वा श्रोतुं शक्नुयाम्।

**Comment by utkrssh** [comment]
@kashcit नम॑स्ते महोदय। ए॒तद्वे॑गनिश्च॒याय॑।
https://github.com/031323/suvak/blob/f8434cb75579c57bfbf70ca98e8c6d0310a6491d/hts/lib/suvak2.js#L88
