### ISSUE TITLE
अस॑न्नतरा॒ अनु॑दात्ताः।

### ISSUE THREAD

**Issue by ujjvlh** [031323/suvak#5]
वा॒क्या॒दौ ये त्वस॑न्नतरा॒ अनु॑दात्ता॒स्तेऽपि॑ पृ॒थक्त॑यता॒ परि॑वर्तयितुं शक्यन्ताम्। येन॒ त ए॑कश्रु॒त्या भि॒द्येर॑न्। @utkrssh

**Comment by utkrssh** [comment]
https://github.com/031323/suvak/blob/38470a6accbdef49a0cdc146d835516b83fe0abc/hts/lib/suvak2.js#L89
