### ISSUE TITLE
npm library

### ISSUE THREAD

**Issue by vvasuki** [031323/suvak#7]
नमामि!

यदि ध्वनिजननाय शुद्ध-js-भाषया ऽन्ततो गत्वा चाल्यते प्रयोक्तृयन्त्रे (नाम back-end server इत्येतद् विना), तर्हि तन् नानाविधजालक्षेत्रेषु सरल-प्रयोगाय npm इत्यस्मिन् प्रकाशनीयम्। स्वजालक्षेत्रेषु विनियोक्तुम् इच्छामि।

**Comment by utkrssh** [comment]
`node`-म॒ध्ये [Web Audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API) न व॑र्तते।
[`suvak2.js`](https://031323.github.io/suvak/suvak2.js) इत्य॒स्य प्र॑योगवि॒धिर्मयात्र॑ लिखि॒तः - [प्र॒यो॒गः](https://github.com/031323/suvak#%E0%A4%AA%E0%A5%8D%E0%A4%B0%E0%A5%92%E0%A4%AF%E0%A5%8B%E0%A5%92%E0%A4%97%E0%A4%83)

**Comment by ujjvlh** [comment]
[`suvak2.js`](https://031323.github.io/suvak/suvak2.js) इ॒दं नाम॑ परिवर्त॒नीय॑म्। न हि शश्व॑दे॒वं स्थातु॑मर्हति। शी॒घ्रं प॑रिव॒र्त्यते॒ चेच्छो॑भ॒नं तत् स्या॑त्। चि॒रे कृ॒ते बा॑ह्यसम्बन्धभ॒ङ्गा भ॑विष्यन्ति, @utkrssh.

**Comment by utkrssh** [comment]
[suvak2.js](https://031323.github.io/suvak/suvak2.js) अ॒स्य कृ॒ते मया॑ [suvak.js](https://031323.github.io/suvak/suvak.js) (`symlink` ) अ॒यम् स्था॒पि॒तः।

**Comment by vvasuki** [comment]
@utkrssh न वर्तताम् node-मध्ये - browser-मध्ये वर्तते चेद् अलम्। 

मम कल्पनैवम् अस्ति -

suvak.js तथा suvakworker.js इति npm द्वारा प्रसारणीयाव् इति। यथा खलु मया https://github.com/sanskrit/sanscript.js इत्यनेन sanscript.js इति निर्माय `npm publish --access public` इत्यनेन npm इत्यत्र प्रकाशयामि। पश्चात् प्रयोक्तारः `npm install @sanskrit-coders/sanscript` इति यथा कृत्वा sanscript.js इति लभन्ते, तथा `npm install suvak` इति कृत्वा suvak.js तथा suvakworker.js लभेरन्।

ततः https://github.com/sanskrit-coders/sanskrit-documentation-theme-hugo/blob/master/webpack_src/js/transliteration.js इत्यत्र यथा `import Sanscript from "@sanskrit-coders/sanscript"; Sanscript.t(textNode.textContent, transliterationSource, transliterationTarget);` इति कृतं , तथा  `import suvak; suvak.bhaashasva(someText, suvak_svr0, suvak_svr1, ....)` इति कृत्वा भाषयितुं शक्नुयुः।

**Comment by utkrssh** [comment]
@vvasuki सा॒धु। ए॒वमे॒व क॑रिष्यते। अ॒हम् npm नाम॑ Node Package Manager जा॒ना॒मि॒ स्म॒। तत्क्ष॑म्यताम्।

**Comment by utkrssh** [comment]
@vvasuki स्था॒पि॒तम् npm म॒ध्ये।
```
$ npm install suvak
```
```js
import * as suvak from './node_modules/suvak/suvak.js';
```
ततः॑ click / keypress इत्य॒स्मात् परं॑ ([ए॒तद्द्र॑ष्ट॒व्य॑म्](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Best_practices#autoplay_policy))-
```js
suvak.bhaashasva('सं॒स्कृ॒त॒वाच॑नाय॒यन्त्र॑मि॒दम्');
suvak.bhaashasva('उ॒दा॒त्ता॒नु॒दा॒त्त॒स्व॒रैःस॒ह',100,150);
```

**Comment by vvasuki** [comment]
`import * as suvak from 'suvak';` इति वा `import suvak;` इति वा यथा सफलं स्यात्, तथा विदधातु। `import * as suvak from './node_modules/suvak/suvak.js';` इति न तावत्शोभनम्। कथं तत् साधनीयम् इति चेत् सरलम् उदाहरणम् -https://github.com/sanskrit/sanscript.js/blob/3d033da7aae0f33ac514b345c9b4b6904e81a03c/package.json

**Comment by vvasuki** [comment]
सद्य एवं दोष उद्भवति -

![image](https://user-images.githubusercontent.com/2664797/119245066-e4e91800-bb93-11eb-8ede-40ba40cf399f.png)

दुष्टपङ्क्तिश् च दृश्यतैवम् - 

`context.audioWorklet.addModule("file:///home/vvasuki/vvasuki-git/kAvya/themes/sanskrit-documentation-theme-hugo/webpack_src/node_modules/suvak/suvak.js".split('/').slice(0,-1).join('/')+'/suvakworker.js').then(() => {arbdh_=true;suvakw=true;prtikrm_();});`

कथम् इद् एवम् local-path गृह्यते? प्रायेण भवता ऽपि `import * as suvakworker from './suvakworker.js';` इति किञ्चिद् विधातुं वरम्। 

https://github.com/sanskrit-coders/sanskrit-documentation-theme-hugo/blob/master/webpack_src/js/text_to_speech.js इति प्रयत्यमानम् - suvak.rundhi() इत्यपि भाषणं रोद्धुम् अपेक्षितं स्यात्।

**Comment by utkrssh** [comment]
-- कथम् इद् एवम् local-path गृह्यते?
webpack तत्राप॑राध्यति॒ यत् `import.meta.url` इत्य॒स्य `"file:///home/vvasuki/vvasuki-git/kAvya/themes/sanskrit-documentation-theme-hugo/webpack_src/node_modules/suvak/suvak.js"` ए॒तत् क॒रोति॑।
अ॒हं ताव॑दे॒वं प्रयु॑नज्मि webpack विना॑ -
```
npm install suvak
cat << EOF > index.html
<html>
<head>
    <meta charset="UTF-8">
</head>
    <body>
    <button id="b1">?</button>
    <script type="module">
    import * as suvak from './node_modules/suvak/suvak.js';
    b1.onclick=()=>{
      suvak.bhaashasva('सं॒स्कृ॒त॒वाच॑नाय॒यन्त्र॑मि॒दम्');
    }
    </script>
    </body>
</html>
EOF
python -m http.server 8000
```
अ[प्ये॒तद्](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) वि॑दि॒तं भव॑तः।

**Comment by utkrssh** [comment]
-- प्रायेण भवता ऽपि import * as suvakworker from './suvakworker.js'; इति किञ्चिद् विधातुं वरम्।
[AudioWorklet](https://developer.mozilla.org/en-US/docs/Web/API/AudioWorkletProcessor)-कृ॒ते नेदानीं॒ याव॑तदे॒वं दृ॒ष्टं क्व॑चित्।

**Comment by utkrssh** [comment]
@vvasuki `suvak.bhashasva` इत्य॒स्मै द॒त्तः शब्दः॑ संहि॒तो भा॑ष्यते। वि॒रा॒म॒चि॒ह्ना उपे॑क्ष्यन्ते। तस्मा॑दे॒वं क्रि॑येत -
```js
transliteratedText.split(/[।॥,]/).forEach(v=>suvak.bhaashasva(v, 100, 150));
```

**Comment by ujjvlh** [comment]
> @vvasuki suvak.bhashasva इत्य॒स्मै द॒त्तः शब्दः॒ संहि॑तो भाष्यते। वि॒रा॒म॒चि॒ह्ना उपे॑क्ष्यन्ते।

`0.0.3` इत्य॒स्मिन् पू॒र्णता॑याः प्रति॒ज्ञा (Promise) यो॑जि॒ता। इ॒दानी॑मे॒वं लि॑खतु, @vvasuki -

```js
return transliteratedText.split( /[।॥,]/).reduce(
   (p, vaakyam) => p.then( _ => ttsOn ? suvak.bhaashasva(vaakyam) : Promise.resolve()),
   Promise.resolve()
);
```

**Comment by vvasuki** [comment]
@utkrssh 

https://github.com/webpack/webpack/issues/11543 इति दृष्ट्वा `const audioWorklet = new URL("./suvakworker.js", import.meta.url);` इति साधु कार्यं करोतीति ज्ञायते।

![image](https://user-images.githubusercontent.com/2664797/119258367-e859bf00-bbe6-11eb-8d1d-f564350c9a7d.png)

किञ्चाग्रे `context.audioWorklet.addModule(audioWorklet.href)).then(() => {arbdh_=true;suvakw=true;prtikrm_();});` इत्यादेशो दुष्फलः - 
![image](https://user-images.githubusercontent.com/2664797/119258408-21922f00-bbe7-11eb-8afd-d4b4fb280cfe.png)


https://github.com/webpack/webpack/issues/11543 इत्यस्मात् कथं विधेयं मयेति किञ्चिज् ज्ञायते?

**Comment by utkrssh** [comment]
@vvasuki 
```js
import { AudioWorklet } from "audio-worklet";
...
context.audioWorklet.addModule(
    new AudioWorklet(new URL("./suvakworker.js", import.meta.url))
).then(() => {arbdh_=true;suvakw=true;prtikrm_();});
```

**Comment by utkrssh** [comment]
@vvasuki 
```json
"devDependencies": {
    "worklet-loader": "^1.0.0"
}
```
