### ISSUE TITLE
suvak_worker आह्वाने प्रश्नः

### ISSUE THREAD

**Issue by vvasuki** [031323/suvak#9]
https://vvasuki.github.io/kAvyam/TIkA/champUH/nItiH/panchatantram/00-kathAmukham/?&comment_style=on इत्यत्र 🎧️चिह्ने नुदिते दृश्यत एवम्  

![image](https://user-images.githubusercontent.com/2664797/119269754-ec9dd080-bc16-11eb-89ea-3fb6e3c813d6.png)

किञ्च ध्वनिर् नायाति। किं कारणं स्यात्? ( साङ्गणकादेशस् त्व् अत्रास्ति - https://github.com/sanskrit-coders/sanskrit-documentation-theme-hugo/blob/83296cf1780fae56fd2b5f1a63713848e54ff240/webpack_src/js/textToSpeech.js#L51  )

**Comment by utkrssh** [comment]
भव॑ता ग्र॒न्थिः प्रस॑ङ्गं॒ न प्रापि॑तः।
https://github.com/031323/suvak/blob/a84c1b3a071e91e57f1ba340eba1783da7da7288/hts/lib/suvak2.js#L67

**Comment by utkrssh** [comment]
click / keypress इत्य॒स्मात् परं॑ ([ए॒तद्द्र॑ष्ट॒व्य॑म्](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Best_practices#autoplay_policy)) `context.resume()` अपि॑ क्रि॒येत॑।

**Comment by vvasuki** [comment]
https://jsfiddle.net/vishvas/rf4mq8ej/ इत्यस्मिन् यद्दर्शितं तत् सम्यक् कार्यं कुरुते।

```

var ekashrutiSvarah = 106.67, udaattaSvarah = 150;
var svaritAnudaattah = ekashrutiSvarah;
var svaritOdaattah = udaattaSvarah;
var sannataraSvarah = 100;
var aadiSvarah = ekashrutiSvarah;
var udaattaadAnudaattasyaSvaritah = true;
var speed = 1.0;

const context = new AudioContext({
  sampleRate: 48000,
  latencyHint: "playback"
});

let url = new URL("https://vvasuki.github.io/kAvyam/non_webpack_js/suvakworker.js")
context.audioWorklet.addModule(url);

function speak() {
    node = new AudioWorkletNode(context, 'suvak-processor');
    node.port.onmessage = (event) => {
        console.log('Message from audio processor received')
        console.log(event)
    };
    node.connect(context.destination);
    console.log("AudioWorkletNode with suvak-processor created and connected to destination.", context.destination)
    let text = "देवो वः सवितोत्पुनातु श्रेष्ठतमाय कर्मणे"
    node.port.postMessage([text,
        Math.log(ekashrutiSvarah), Math.log(udaattaSvarah), Math.log(svaritAnudaattah), Math.log(svaritOdaattah), Math.log(sannataraSvarah), Math.log(aadiSvarah),
        udaattaadAnudaattasyaSvaritah, speed]);
}
```

किन्तु, पुनः पुनः ` new AudioWorkletNode` इति कुतः स्यात्? सकृत् सृष्टस्य ध्वन्यङ्गस्य पुनरुपयोगः कुतो न सम्भवति?

तथा SuvakProcessor इत्यस्य मूलं दिदृक्षे, screen-cast कृत्वा तत् कथं कार्यं करोतीति ब्रूते चेन् मोदाय बहु।

**Comment by vvasuki** [comment]
उपरि ekashrutiSvarah, aadiSvarah इति सङ्ख्याद्वयं कुतो नामापेक्षितम्?

**Comment by ujjvlh** [comment]
> उपरि ekashrutiSvarah, aadiSvarah इति सङ्ख्याद्वयं कुतो नामापेक्षितम्?

@vvasuki  येन॒ काभि॑श्चित् पारम्परिकरी॒तिभि॒रपि॒ वाच॑नं स॒म्भवे॑त्।

**Comment by utkrssh** [comment]
> तथा SuvakProcessor इत्यस्य मूलं दिदृक्षे, screen-cast कृत्वा तत् कथं कार्यं करोतीति ब्रूते चेन् मोदाय बहु।
[अत्र॑](https://github.com/031323/suvak/tree/master/hts/lib) `*.c, pre.js, worker.js` इत्ये॒तासु॒ मूल॑म् । अप्य॑पराह्णपञ्चवाद॒नं यु॒क्तं  screen-cast-कृ॒ते ?

**Comment by vvasuki** [comment]
> अप्य॑पराह्णपञ्चवाद॒नं यु॒क्तं screen-cast-कृ॒ते ?

यथासौकर्यं भवान् कृत्वा (linux - obsstudio) प्रकाश्य चित्रसङ्केतम् प्रेषयतु। किमत्र तत्त्वम्, कथं कार्यं करोति, ध्वनने स्थिति-जालम् (state-diagram) कथं दृश्येतेत्यादिकं वदतु।

**Comment by vvasuki** [comment]
> 
> किन्तु, पुनः पुनः ` new AudioWorkletNode` इति कुतः स्यात्? सकृत् सृष्टस्य ध्वन्यङ्गस्य पुनरुपयोगः कुतो न सम्भवति (https://jsfiddle.net/vishvas/268scrvb/1/ इतीक्षताम्)?
> 

अयम् प्रश्नो न  विस्मृतः खलु?

**Comment by utkrssh** [comment]
> Returning false from `process()` method will mark the processor inactive and the WebAudio engine will not invoke the method anymore. To keep the processor alive, the method must return true. Otherwise, the node/processor pair will be garbage collected by the system eventually.

विस्मृ॑त ए॒वासी॑त्। यदा॑ AudioWorkletProcessor ध्व॒नि॒य॒न्त्रस्य॒ स्थग॑नं क्रि॒यते॒ तदा॒ तस्य॒ मार्ज॑नं (garbage collection) भवति। यथा॑ वाक्यान्त॒रेषु॒ स्थग॑नं॒ न क्रि॒येत॒ तथा॑ कर॒णीयं॒ मया॑ `suvakworker.js, suvak.js` इत्ये॒तयोः॑।
